#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Hagiwara Kouki
# SPDX-License-Identifier: BSD-3-Clause

#階乗を計算する

import sys


def factorial(n):
    if n == 0 or n == 1:
        return 1
    return n * factorial(n - 1)

if __name__ == "__main__":
    try:
        n = int(input(""))
        print(factorial(n))
    except ValueError:
        print("Please enter a valid integer.")
